### ISSUE TITLE
Support PUID/PGID env vars

### ISSUE THREAD

**Issue by timkelty** [usma0118/magnet2torrent#16]
**Is your feature request related to a problem? Please describe.**
I'm trying to use this with unRaid, with a mounted bind volume for `/torrents`. 

**Describe the solution you'd like**
Support passing env vars `PUID` and `PGID`.

**Additional context**
Here's what the logs look like currently:
```
[2022-03-02 12:19:22] Processing file: 637818202878625691-LinuxTracker-Kali linux 2022 1 Virtualbox 64bit OVA.magnet
INFO:__main__:Processing file: 637818202878625691-LinuxTracker-Kali linux 2022 1 Virtualbox 64bit OVA.magnet
[2022-03-02 12:19:22] Acquiring torrent metadata for hash 1e4cc12d6117f7d1bce4d7df164eecf3c1875f8c
INFO:__main__:Acquiring torrent metadata for hash 1e4cc12d6117f7d1bce4d7df164eecf3c1875f8c
Traceback (most recent call last):
File "/app/main.py", line 100, in <module>
program.main()
File "/app/main.py", line 67, in main
torrent_path=client.magnet2torrent(magnet_contents,output)
File "/app/torrent/torrentclient.py", line 117, in magnet2torrent
with open(output, 'wb') as f:
PermissionError: [Errno 13] Permission denied: '/torrent/kali-linux-2022.1-virtualbox-amd64-ova.torrent'
```

This is a someone standard paradigm other docker images use:
- https://github.com/linuxserver/docker-baseimage-ubuntu/blob/544ef4e74f832dc5e32f4b3967a23ed3f56c8cf8/root/etc/cont-init.d/10-adduser
- https://github.com/haugene/docker-transmission-openvpn/blob/e6fd367db74075e2b507d420191a55a43b5e8d90/transmission/userSetup.sh

**Comment by usma0118** [comment]
What version of docker are you running on unraid?

**Comment by timkelty** [comment]
```
Docker version 20.10.5, build 55c4c88
```
